### ISSUE TITLE
Bug in timings report

### ISSUE THREAD

**Issue by markmac99** [ukmda/ukmda-dataprocessing#353]
timingMetrics was crashing as some lines didn't contain the runtime seconds. 
```
<13>Jan  6 11:02:47 nightlyJob: RUNTIME 3886 finished nightlyJob
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/wmpl/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ec2-user/miniconda3/envs/wmpl/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/prod/ukmon_pylib/metrics/timingMetrics.py", line 141, in <module>
    getLogStats(nightf, matchf)
  File "/home/ec2-user/prod/ukmon_pylib/metrics/timingMetrics.py", line 82, in getLogStats
    secs.append(int(spls[5]))
ValueError: invalid literal for int() with base 10: 'start'
```

**Comment by markmac99** [comment]
identified cameraStatusReport.sh as the culprit - forgot to include $SECONDS in the logger calls.
